<a href="https://colab.research.google.com/github/gomathiaravindan/Machine_Learning/blob/main/1818121_OST_Exp_no_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a NumPy program to compute sum of two arrays



In [ ]:
import numpy as np
 
arr1 = np.array([3, 2, 1])
arr2 = np.array([1, 2, 3])
   
print ("1st array : ", arr1)  
print ("2nd array : ", arr2)  
   
out_arr = np.add(arr1, arr2)  
print ("added array : ", out_arr)  

1st array :  [3 2 1]
2nd array :  [1 2 3]
added array :  [4 4 4]


Write a NumPy program to find the sum of the array


In [ ]:
import numpy as np
num = np.arange(36)
arr1 = np.reshape(num, [4, 9])
print("Original array:")
print(arr1)
result  = np.sum(arr1)
print("\nSum of all elements:")
print(result)


Original array:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]

Sum of all columns:
630


Write a NumPy program to find the square root of two array


In [ ]:
# Python program explaining 
# numpy.sqrt() method 

# importing numpy 
import numpy as goms 

# applying sqrt() method on integer numbers 
arr1 = goms.sqrt([1, 4, 9, 16]) 
arr2 = goms.sqrt([6, 10, 18]) 

print("square-root of an array1 : ", arr1) 
print("square-root of an array2 : ", arr2) 


square-root of an array1 :  [1. 2. 3. 4.]
square-root of an array2 :  [2.44948974 3.16227766 4.24264069]


Write a NumPy program to find the sum of each column and each row of two array


In [ ]:
import numpy as np
x = np.array([[12,13],[2,9]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[12 13]
 [ 2  9]]
Sum of each column:
[14 22]
Sum of each row:
[25 11]


Write a NumPy program to find the transpose of two array


In [ ]:
# import the important module in python 
import numpy as np 
			
# make matrix with numpy 
gfg = np.matrix('[4, 1, 10; 12, 3, 1; 1, 2, 3]') 
			
# applying matrix.transpose() method 
goms = gfg.transpose() 
	
print(goms) 


[[ 4 12  1]
 [ 1  3  2]
 [10  1  3]]
